spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/driving_today?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password:

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: none
    show-sql: true

  data:
    mongodb:
      database: driving-today
      uri: mongodb://localhost:27017/driving-today
    redis:
      host: localhost
      port: 6379

cloud:
  aws:
    s3:
      bucket: { 버킷 이름 }
    credentials:
      access-key: { 액세스키 }
      secret-key: { 시크릿키 }
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false

jwt:
  credentials:
    secret-key: { 토큰 키 }
  access-token:
    expire-length: 50000
  refresh-token:
    expire-length: 50000
