export const dummydata = [
  {
    distance: 72,
    instructorId: 1,
    latitude: 37.487,
    longitude: 127.045,
    cert: true,
    instructorImage: 'https://picsum.photos/200',
    pricePerHour: 29000,
    instructorName: '오정진',
    academyName: '강남차동자전운문전학원',
  },
  {
    distance: 36,
    instructorId: 2,
    latitude: 37.475,
    longitude: 127.075,
    cert: false,
    instructorImage: 'https://picsum.photos/200',
    pricePerHour: 42000,
    instructorName: '오정진',
    academyName: '강남차동자전운문전학원',
  },
  {
    distance: 89,
    instructorId: 3,
    latitude: 37.499,
    longitude: 127.023,
    cert: true,
    instructorImage: 'https://picsum.photos/200',
    pricePerHour: 19000,
    instructorName: '오정진',
    academyName: '강남차동자전운문전학원',
  },
  {
    distance: 21,
    instructorId: 4,
    latitude: 37.481,
    longitude: 127.057,
    cert: false,
    instructorImage: 'https://picsum.photos/200',
    pricePerHour: 34000,
    instructorName: '오정진',
    academyName: '강남차동자전운문전학원',
  },
  {
    distance: 68,
    instructorId: 5,
    latitude: 37.466,
    longitude: 127.088,
    cert: true,
    instructorImage: 'https://picsum.photos/200',
    pricePerHour: 47000,
    instructorName: '오정진',
    academyName: '강남차동자전운문전학원',
  },
  {
    distance: 45,
    instructorId: 6,
    latitude: 37.492,
    longitude: 127.012,
    cert: false,
    instructorImage: 'https://picsum.photos/200',
    pricePerHour: 13000,
    instructorName: '오정진',
    academyName: '강남차동자전운문전학원',
  },
  {
    distance: 53,
    instructorId: 7,
    latitude: 37.505,
    longitude: 127.035,
    cert: true,
    instructorImage: 'https://picsum.photos/200',
    pricePerHour: 29000,
    instructorName: '오정진',
    academyName: '강남차동자전운문전학원',
  },
  {
    distance: 86,
    instructorId: 8,
    latitude: 37.482,
    longitude: 127.068,
    cert: false,
    instructorImage: 'https://picsum.photos/200',
    pricePerHour: 46000,
    instructorName: '오정진',
    academyName: '강남차동자전운문전학원',
  },
  {
    distance: 10,
    instructorId: 9,
    latitude: 37.491,
    longitude: 127.097,
    cert: true,
    instructorImage: 'https://picsum.photos/200',
    pricePerHour: 32000,
    instructorName: '오정진',
    academyName: '강남차동자전운문전학원',
  },
  {
    distance: 93,
    instructorId: 10,
    latitude: 37.497,
    longitude: 127.045,
    cert: false,
    instructorImage: 'https://picsum.photos/200',
    pricePerHour: 44000,
    instructorName: '오정진',
    academyName: '강남차동자전운문전학원',
  },
]
