export const dummydata = [
  {
    distance: 73,
    instructorId: 1,
    latitude: 34.257,
    longitude: 126.891,
    cert: true,
    instructorImage: 'https://picsum.photos/200',
    pricePerHour: 29000,
    instructorName: '오정진',
    academyName: '강남차동자전운문전학원',
  },
  {
    distance: 15,
    instructorId: 2,
    latitude: 35.628,
    longitude: 130.514,
    cert: false,
    instructorImage: 'https://picsum.photos/200',
    pricePerHour: 42000,
    instructorName: '오정진',
    academyName: '강남차동자전운문전학원',
  },
  {
    distance: 87,
    instructorId: 3,
    latitude: 33.752,
    longitude: 127.567,
    cert: true,
    instructorImage: 'https://picsum.photos/200',
    pricePerHour: 19000,
    instructorName: '오정진',
    academyName: '강남차동자전운문전학원',
  },
  {
    distance: 41,
    instructorId: 4,
    latitude: 37.194,
    longitude: 125.698,
    cert: false,
    instructorImage: 'https://picsum.photos/200',
    pricePerHour: 34000,
    instructorName: '오정진',
    academyName: '강남차동자전운문전학원',
  },
  {
    distance: 62,
    instructorId: 5,
    latitude: 36.215,
    longitude: 129.109,
    cert: true,
    instructorImage: 'https://picsum.photos/200',
    pricePerHour: 47000,
    instructorName: '오정진',
    academyName: '강남차동자전운문전학원',
  },
  {
    distance: 24,
    instructorId: 6,
    latitude: 35.782,
    longitude: 126.485,
    cert: false,
    instructorImage: 'https://picsum.photos/200',
    pricePerHour: 13000,
    instructorName: '오정진',
    academyName: '강남차동자전운문전학원',
  },
  {
    distance: 50,
    instructorId: 7,
    latitude: 34.912,
    longitude: 127.976,
    cert: true,
    instructorImage: 'https://picsum.photos/200',
    pricePerHour: 29000,
    instructorName: '오정진',
    academyName: '강남차동자전운문전학원',
  },
  {
    distance: 83,
    instructorId: 8,
    latitude: 37.012,
    longitude: 130.321,
    cert: false,
    instructorImage: 'https://picsum.photos/200',
    pricePerHour: 46000,
    instructorName: '오정진',
    academyName: '강남차동자전운문전학원',
  },
  {
    distance: 7,
    instructorId: 9,
    latitude: 36.185,
    longitude: 124.881,
    cert: true,
    instructorImage: 'https://picsum.photos/200',
    pricePerHour: 32000,
    instructorName: '오정진',
    academyName: '강남차동자전운문전학원',
  },
  {
    distance: 96,
    instructorId: 10,
    latitude: 37.579,
    longitude: 130.019,
    cert: false,
    instructorImage: 'https://picsum.photos/200',
    pricePerHour: 44000,
    instructorName: '오정진',
    academyName: '강남차동자전운문전학원',
  },
]
